[package]
name = "simple-companion"
description = "Companion for the Simplicity language"
version = "0.1.0"
edition = "2021"
authors = ["Christian Lewe"]
license = "CC0-1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simplicity = { git = "https://github.com/ElementsProject/rust-simplicity", branch = "master" }
base64 = "0.21"
clap = { version = "4.3", features = ["derive"] }
